# -*- coding: utf-8 -*-
"""Another copy of Project without.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tacO-O8Z9eu9w8IqN1dsklEAl-v4_Zcw

# Digital Learning Analytics — Course Completion (Classification)

The Problem:

Most online learning platforms suffer from very high dropout rates. A large number of students start a course but never finish it. Platforms need a way to detect these students early before they leave.

Project Goal:

Build a Machine Learning model that analyzes student activity and predicts whether a student will finish the course or drop out.

## 1) Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                              roc_auc_score, classification_report, confusion_matrix,
                              ConfusionMatrixDisplay)

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

try:
    from xgboost import XGBClassifier
    XGB_AVAILABLE = True
except ImportError:
    XGB_AVAILABLE = False
    print("xgboost غير مثبت – pip install xgboost لو عايز تجربه")

"""## 2) Load Data"""

df = pd.read_csv("data/digital_learning_analytics_100k.csv")
df.head()

df.info()

"""## 3) Explore the Data (EDA)"""

# 1. التأكد إن مفيش أي عمود نصي متبقي (لازم يطبع بس int64 أو float64 أو bool)
print(df.dtypes.value_counts())

# 2. التأكد إن مفيش قيم مفقودة (Missing Values)
print("إجمالي القيم الناقصة:", df.isnull().sum().sum())

print(df.isnull().sum()[df.isnull().sum() > 0])

col_has_null= ['gamification_engagement','essay_vocabulary_richness', 'essay_coherence_score','forum_posts','peer_review_given',
               'content_recommendations_followed','learning_efficiency_score']
for  col in col_has_null:
    sns.boxplot(data = df , x=df[col])
    plt.show()

#we have outlayer so we should put (median)
for col in col_has_null:
    df[col] = df[col].fillna(df[col].median())

target = "course_completed"
sns.countplot(x=target, data=df)
plt.title("Course Completion Distribution")
plt.show()

numeric_cols_preview = df.select_dtypes(include=[np.number]).columns
plt.figure(figsize=(14, 10))
sns.heatmap(df[numeric_cols_preview].corr(), cmap="coolwarm", center=0)
plt.title("Correlation Heatmap")
plt.show()

"""## 4) Feature Engineering"""

#do feature engenieer
df['enrollment_date'] = pd.to_datetime(df['enrollment_date'])
df['last_activity_date'] = pd.to_datetime(df['last_activity_date'])

# حساب الفرق بالأيام وإنشاء عمود جديد
df['days_active'] = (df['last_activity_date'] - df['enrollment_date']).dt.days

columns_to_drop = [
    'learner_id',
    'skill_post_score',
    'mastery_score',
    'time_to_mastery_hours',
    'country','enrollment_date'
    ,'last_activity_date'
    ,'days_active'
    , 'course_duration_weeks']

df.drop(columns=columns_to_drop,inplace=True)
df.shape

#convert obj --> numerical

education_map = {
    'High School': 0,
    'Some College': 1,
    'Undergraduate': 2,
    'Graduate': 3,
    'Professional Certificate': 4,
    'Doctoral': 5
}

df['education_level'] = df['education_level'].map(education_map)



categorical_cols = [
    'gender',
    'employment_status',
    'app_category',
    'essay_topic_category',
    'mooc_platform',
    'course_category',
    'learning_path_type'
]
encoder = LabelEncoder()
for col in categorical_cols:
    if col in df.columns:
        df[col] = encoder.fit_transform(df[col].astype(str))

"""## 5) Split Features and Target

## 6) Train / Test Split
"""



x= df.drop('course_completed', axis=1)
y=df['course_completed']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

scaled = StandardScaler()
x_train_scaled = scaled.fit_transform(x_train)
x_test_scaled = scaled.transform(x_test)
print(x_train.shape)
print(x_test.shape)

"""## 8) Model Training & Comparison

logistic regression
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score


lr_model = LogisticRegression(max_iter=1000, class_weight='balanced')
lr_model.fit(x_train_scaled, y_train)


lr_pred = lr_model.predict(x_test_scaled)
lr_proba = lr_model.predict_proba(x_test_scaled)[:, 1]

print('--- Logistic Regression ---')
print('Accuracy:', round(accuracy_score(y_test, lr_pred), 4))
print('ROC AUC:', round(roc_auc_score(y_test, lr_proba), 4))
print('\nClassification Report:\n', classification_report(y_test, lr_pred))

"""Naive Bayes"""

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

nb_model = GaussianNB()
nb_model.fit(x_train_scaled, y_train)

nb_pred = nb_model.predict(x_test_scaled)
nb_proba = nb_model.predict_proba(x_test_scaled)[:, 1]

print("--- Naive Bayes ---")
print("Accuracy:", round(accuracy_score(y_test, nb_pred), 4))
print("ROC AUC:", round(roc_auc_score(y_test, nb_proba), 4))
print("\nClassification Report:\n", classification_report(y_test, nb_pred))

"""Decision Tree"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score


dt_model = DecisionTreeClassifier(max_depth=10, random_state=42)
dt_model.fit(x_train_scaled, y_train)

dt_pred = dt_model.predict(x_test_scaled)
dt_proba = dt_model.predict_proba(x_test_scaled)[:, 1]

print("--- Decision Tree ---")
print("Accuracy:", round(accuracy_score(y_test, dt_pred), 4))
print("ROC AUC:", round(roc_auc_score(y_test, dt_proba), 4))
print("\nClassification Report:\n", classification_report(y_test, dt_pred))

"""K-Nearest Neighbors (KNN)"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score


knn_model = KNeighborsClassifier(n_neighbors=15, n_jobs=-1)
knn_model.fit(x_train_scaled, y_train)

knn_pred = knn_model.predict(x_test_scaled)
knn_proba = knn_model.predict_proba(x_test_scaled)[:, 1]

print("--- KNN ---")
print("Accuracy:", round(accuracy_score(y_test, knn_pred), 4))
print("ROC AUC:", round(roc_auc_score(y_test, knn_proba), 4))
print("\nClassification Report:\n", classification_report(y_test, knn_pred))

"""Support Vector Machine (SVM)"""

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score
from sklearn.svm import SVC


svm_model = SVC(probability=False, class_weight='balanced')
svm_model.fit(x_train_scaled, y_train)


svm_pred = svm_model.predict(x_test_scaled)
svm_scores = svm_model.decision_function(x_test_scaled)

print('--- SVM ---')
print('Accuracy:', round(accuracy_score(y_test, svm_pred), 4))
print('ROC AUC:', round(roc_auc_score(y_test, svm_scores), 4))
print('\nClassification Report:\n', classification_report(y_test, svm_pred))

"""Random Forest"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score


rf_model = RandomForestClassifier(
    n_estimators=50,
    max_depth=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)
rf_model.fit(x_train_scaled, y_train)

rf_pred = rf_model.predict(x_test_scaled)
rf_proba = rf_model.predict_proba(x_test_scaled)[:, 1]


print("--- Random Forest ---")
print("Accuracy:", round(accuracy_score(y_test, rf_pred), 4))
print("ROC AUC:", round(roc_auc_score(y_test, rf_proba), 4))
print("\nClassification Report:\n", classification_report(y_test, rf_pred))

"""Bagging Classifier"""

from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score


bag_model = BaggingClassifier(n_estimators=50, random_state=42, n_jobs=-1)
bag_model.fit(x_train_scaled, y_train)

bag_pred = bag_model.predict(x_test_scaled)
bag_proba = bag_model.predict_proba(x_test_scaled)[:, 1]


print("--- Bagging ---")
print("Accuracy:", round(accuracy_score(y_test, bag_pred), 4))
print("ROC AUC:", round(roc_auc_score(y_test, bag_proba), 4))
print("\nClassification Report:\n", classification_report(y_test, bag_pred))

"""XGBoost"""

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score


xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)


xgb.fit(x_train_scaled, y_train)


y_pred_xgb = xgb.predict(x_test_scaled)
y_proba_xgb = xgb.predict_proba(x_test_scaled)[:, 1]


print("=== XGBoost Classification Report ===")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_proba_xgb):.4f}")

"""## 9) Results Comparison"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

# 1. تجميع النتائج من كافة الموديلات (بما فيها XGBoost بشكل مباشر)
results = {
    "Logistic Regression": {
        "accuracy": accuracy_score(y_test, lr_pred),
        "precision": precision_score(y_test, lr_pred),
        "recall": recall_score(y_test, lr_pred),
        "f1": f1_score(y_test, lr_pred),
        "roc_auc": roc_auc_score(y_test, lr_proba),
    },
    "Naive Bayes": {
        "accuracy": accuracy_score(y_test, nb_pred),
        "precision": precision_score(y_test, nb_pred),
        "recall": recall_score(y_test, nb_pred),
        "f1": f1_score(y_test, nb_pred),
        "roc_auc": roc_auc_score(y_test, nb_proba),
    },
    "Decision Tree": {
        "accuracy": accuracy_score(y_test, dt_pred),
        "precision": precision_score(y_test, dt_pred),
        "recall": recall_score(y_test, dt_pred),
        "f1": f1_score(y_test, dt_pred),
        "roc_auc": roc_auc_score(y_test, dt_proba),
    },
    "KNN": {
        "accuracy": accuracy_score(y_test, knn_pred),
        "precision": precision_score(y_test, knn_pred),
        "recall": recall_score(y_test, knn_pred),
        "f1": f1_score(y_test, knn_pred),
        "roc_auc": roc_auc_score(y_test, knn_proba),
    },
    "SVM": {
        "accuracy": accuracy_score(y_test, svm_pred),
        "precision": precision_score(y_test, svm_pred),
        "recall": recall_score(y_test, svm_pred),
        "f1": f1_score(y_test, svm_pred),
        "roc_auc": roc_auc_score(y_test, svm_scores),
    },
    "Random Forest": {
        "accuracy": accuracy_score(y_test, rf_pred),
        "precision": precision_score(y_test, rf_pred),
        "recall": recall_score(y_test, rf_pred),
        "f1": f1_score(y_test, rf_pred),
        "roc_auc": roc_auc_score(y_test, rf_proba),
    },
    "Bagging": {
        "accuracy": accuracy_score(y_test, bag_pred),
        "precision": precision_score(y_test, bag_pred),
        "recall": recall_score(y_test, bag_pred),
        "f1": f1_score(y_test, bag_pred),
        "roc_auc": roc_auc_score(y_test, bag_proba),
    },
    "XGBoost": {
        "accuracy": accuracy_score(y_test, y_pred_xgb),
        "precision": precision_score(y_test, y_pred_xgb),
        "recall": recall_score(y_test, y_pred_xgb),
        "f1": f1_score(y_test, y_pred_xgb),
        "roc_auc": roc_auc_score(y_test, y_proba_xgb),
    },
}

# 2. تحويل القاموس لـ DataFrame وعرضه مرتباً بحسب ROC-AUC
results_df = pd.DataFrame(results).T.sort_values("roc_auc", ascending=False)
display(results_df.round(4))

# 3. الرسم البياني مع كتابة القيم على الأشرطة
plt.figure(figsize=(9, 5))
ax = results_df["roc_auc"].plot(kind="barh", color="steelblue")
plt.xlabel("ROC-AUC Score")
plt.title("Model Comparison - ROC-AUC")
plt.gca().invert_yaxis()

# إضافة قيم الـ ROC-AUC على الأشرطة
for p in ax.patches:
    ax.annotate(
        f"{p.get_width():.4f}",
        (p.get_width(), p.get_y() + p.get_height() / 2.0),
        ha="left",
        va="center",
        xytext=(5, 0),
        textcoords="offset points",
    )

plt.tight_layout()
plt.show()

"""## 10) Best Model — Detailed Evaluation"""

from sklearn.metrics import classification_report


fitted_models = {
    "Logistic Regression": lr_model,
    "Naive Bayes": nb_model,
    "Decision Tree": dt_model,
    "KNN": knn_model,
    "SVM": svm_model,
    "Random Forest": rf_model,
    "Bagging": bag_model,
    "XGBoost": xgb,
}




best_model_name = results_df.index[0]
best_model = fitted_models[best_model_name]


y_pred_best = best_model.predict(x_test_scaled)


print(f"Best model: {'XGBoost'}\n")
print(classification_report(y_test, y_pred_best, target_names=["Not Completed", "Completed"]))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix


cm = confusion_matrix(y_test, y_pred_best)


disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Not Completed", "Completed"])


disp.plot(cmap="Blues")
plt.title(f"Confusion Matrix — {best_model_name}")
plt.show()

"""## 11) Feature Importance"""

import matplotlib.pyplot as plt
import numpy as np


feature_names = (
    x_train.columns
    if 'x_train' in locals()
    else df.drop('course_completed', axis=1).columns
)


tree_based = ["Random Forest", "Decision Tree", "XGBoost"]
importance_model_name = next((m for m in tree_based if m in fitted_models), None)

if importance_model_name:
    importance_model = fitted_models[importance_model_name]
    importances = importance_model.feature_importances_


    top_idx = np.argsort(importances)[-15:]


    plt.figure(figsize=(8, 6))
    plt.barh(range(len(top_idx)), importances[top_idx], color="teal")
    plt.yticks(range(len(top_idx)), [feature_names[i] for i in top_idx])
    plt.xlabel("Importance")
    plt.title(f"Top 15 Feature Importances — {importance_model_name}")
    plt.tight_layout()
    plt.show()
else:
    print("لا يوجد نموذج قائم على الأشجار في fitted_models لاستخراج Feature Importances.")

import joblib
import os

# إنشاء فولدر للموديلات إن لم يكن موجوداً
os.makedirs("models", exist_ok=True)

# حفظ الـ Scaler وأفضل نموذج
joblib.dump(scaled, "models/scaler.pkl")
joblib.dump(best_model, "models/best_model.pkl")

print("تم حفظ الموديل والـ Scaler بنجاح في مجلد models!")